config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pins

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  get 'home/index'

  get '/home' => 'home#home'

  match '/users/:id/add_email' => 'users#add_email', via: [:get, :patch, :post], :as => :add_user_email

  root 'home#index'

end

app/models/pin.rb
# == Schema Information
#
# Table name: pins
#
#  id          :integer          not null, primary key
#  title       :string(70)
#  description :text
#  status      :integer          default(2)
#  user_id     :integer          not null
#  category_id :integer          not null
#  created_at  :datetime
#  updated_at  :datetime
#  type_id     :integer          not null
#

class Pin < ActiveRecord::Base
  belongs_to :user
  belongs_to :type
  has_many :multimedias

  acts_as_taggable # Alias for acts_as_taggable_on :tags

  before_save :default_category

  enum status: [:inactive, :pending, :active] unless instance_methods.include? :status

  # validations
  validates :title, length: { maximum: 70 }
  validates :type_id, presence: true

  private 

  def default_category
    self.category_id = 1
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :set_type, only: [:show, :edit, :new]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def set_type
      @type = Type.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :status, :user_id, :type_id)
    end
end

 

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_for(@pin, :html => { :multipart => true, :id => "fileupload" }) do |f| %>
 
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
     
  <div class="field">
    <span class="btn btn-success fileinput-button">
      <i class="icon-plus"></i>
      <span>Add files...</span>
      <input id="file" type="file" name="files[]" multiple>
    </span>
    
    <!-- The global progress bar -->
    <div id="progress" class="progress">
        <div class="progress-bar progress-bar-success"></div>
    </div>
    <!-- The container for the uploaded files -->
    <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
  </div> 

  <div class="field">
    <%= f.label :type_id %><br>
    <%= select_tag "pin[type_id]", options_from_collection_for_select(@type, "id", "name", @pin.type_id), prompt: "Select something" %>
    
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
 
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>User</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.title %></td>
        <td><%= pin.description %></td>
        <td><%= pin.status %></td>
        <td><%= pin.user_id %></td>
        <td><%= pin.category_id %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pin.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @pin.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @pin.user_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @pin.category_id %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>